[package]
name = "ocr_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.6.1"
actix-web = "4.0"
futures = "0.3.30"
leptess = "0.14.0"
sanitize-filename = "0.5.0"


